version: "3.7"

services:
  elasticsearch:
     image: docker.elastic.co/elasticsearch/elasticsearch:8.13.2
     container_name: elasticsearch
     ports:
       - "9200:9200"
     environment:
       - discovery.type=single-node
       - TAKE_FILE_OWNERSHIP=true
       - xpack.security.enabled=false
       - network.host=0.0.0.0
     healthcheck:
       test: [ "CMD", "curl", "-XGET", "http://localhost:9200" ]
       interval: 20s
       timeout: 10s
       retries: 5

  slt_api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: slt_api
    ports:
      - "1234:8001"
      - "1233:7890"
    depends_on:
      elasticsearch:
        condition: service_healthy